## **Import Libary**

In [1]:
import numpy as np

# **Info about numpy list**

In [ ]:
v = np.array([[1,2,3],[4,5,6]]) #array 2-D
print(v.itemsize) #Comprimento de um elemento de matriz em bytes.
print(len(v)) #nº de arrays
print(v.size) #Number of elements in the array.
print(v.nbytes) #Total bytes consumed by the elements of the array.
# nbytes =  itemsize * size

## **Creating array**

#### Creating array 0-D

In [ ]:
v = np.array(42) #criando uma array 0-D de valor 42
print(v)
print(type(v)) #tipo da variavel
print(v.ndim) #dimensao da variavel

#### Creating array 1-D

In [ ]:
v = np.array([1,2,3]) #criando uma array 1-D
print(v)
print(v.dtype) #tipo de dados

#### Creating array 1-D and specify dtype

In [18]:
v = np.array([1,2,3],dtype='float64') #criando uma array 1-D de tipo de dados = 'float64'
print(v)
print(v.dtype) #tipo de dados

[1. 2. 3.]
float64


#### Creating array 2-D

In [ ]:
v = np.array([[1,2,3],[4,5,6]]) #criando uma array 2-D
print(v)
print(v.dtype) #tipo de dados

#### Creating array 3-D with a specify dtype

In [ ]:
v = np.array([ [[1, 0, 1], [0,0, 1]], [[1, 1, 0], [0, 0, 1]] ],dtype=bool) #criando uma array 3-D de tipo de dados = bool
print(v)
print(v.dtype) #tipo de dados

#### Creating a empty array 1-D

In [ ]:
v = np.empty(4,'int64') #Retorne uma nova matriz de 1-D de 4 elementos do tipo int64 sem inicializar entradas
print(v)
print(v.dtype)

#### Creating a empty array 2-D

In [ ]:
v = np.empty((4,3),int) #Retorne uma nova matriz 4 linhas e 3 colunas de tipo int sem inicializar entradas
print(v)
print(v.dtype)

#### Creating a empty array 2-D with another way to give a dtype

In [ ]:
v = np.empty((2,2),dtype='float32') #Retorne uma nova matriz 2 linhas e 2 colunas de tipo float32 sem inicializar entradas
print(v)
print(v.dtype) #pode usar dtype ou n

#### Creating a one array 1-D

In [ ]:
"""CRIANDO ARRAY ONES"""
v = np.ones(5,int) #retorna uma matriz de 5 elementos 1-D do tipo int
print(v)
print(v.dtype)

#### Creating a 2-D one array

In [ ]:
v = np.ones((4,4),dtype='float64') #retorna uma matriz de 4 linhas e 4 colunas do tipo float64 do tipo 2-D
print(v)
print(v.dtype) #pdoe usar dtype ou n

#### Creating a zero array 1-D

In [ ]:
v = np.zeros(5,float) #retorna uma matriz de 5 elementos 1-D do tipo float
print(v)
print(v.dtype)

#### Creating a zero array 2-D

In [ ]:
v = np.zeros((5,5),dtype='int32') #retorna uma matriz de 5linhas e 5 colunas 2-D do tipo int32
print(v)
print(v.dtype) #pode usar dtype ou n

#### Creating a full array 1-D

In [ ]:
v = np.full(8,3,dtype = 'float') # retorna uma matriz de 8 elementos com valor 3 do tipo float
print(v)
print(v.dtype)

#### Creating a full array 2-D

In [ ]:
v = np.full((5,5),2,dtype = 'int32') # retorna uma matriz de 5 linhas e 5 colunas com valor 2 do tipo int32
print(v)
print(v.dtype)

#### Creating a arange 1-D

In [ ]:
v = np.arange(10,dtype='float') # retorna uma matriz de 1-D de 0 a 9 do tipo float
print(v)
print(v.dtype)

#### Creating a arange 1-D with a initial and end

In [ ]:
v = np.arange(1,16,dtype='int32') # retorna uma matriz de 1-D de 1 a 15 do tipo int32
print(v)
print(v.dtype)

#### Creating a linspace 1-D

In [ ]:
v = np.linspace(0,3,10,dtype='float',endpoint = False) #vetor de 0 a 3 com 10 posicoes sem contar o ultimo pelo endpoint = False (default = True)
print(v)
print(v.dtype)


#### Creating a array by de diagonal

In [ ]:
v = np.diag(np.array([1,2,3,4])) #matriz com diagonal determinada pela array 
print(v)

#### Creating a array by a diagonal (variable)

In [ ]:
diagonal = np.array([5,6])
v = np.diag(diagonal) #matriz com diagonal determinada pela variavel
print(v)

#### Creating a array (Random.rand) 1-D

In [ ]:
v = np.random.rand(4) #retorna uma matriz 1-D com 4 numeros
print(v)
print(v.dtype) #NÃO PODE DETERMINAR O TIPO

#### Creating a array (Random.rand) 2-D

In [ ]:
v = np.random.rand(4,4) #retorna uma matriz 1-D com 4 linhas e 4 colunas com numeros aleatorios
print(v)
print(v.dtype) #NÃO PODE DETERMINAR O TIPO

#### Creating a eye array

In [ ]:
v = np.eye(2,dtype=float) #cria uma array 2x2 do tipo float com diagonais de 1
print(v)
print(v.dtype)

# **Sort**

In [ ]:
vetor = np.array([3,1,1,5,1,2,7,62,1,5,6,7,4,3]) #array 1-D desordem
ordem_correta = np.sort(vetor) #array com ordem correta #copia
print(ordem_correta)

# **Concatenate arrays**

### Concatenate

In [ ]:
v1 = np.arange(1,11,dtype='int32')  #criando uma array 1-D
v2 = np.arange(11,21,dtype='int32') #criando uma array 1-D
vetor_junto = np.concatenate((v1,v2))# concatenando as 2
print(vetor_junto)

In [ ]:
v1 = np.array([[1,2,3],[4,5,6]],dtype='int64')  #criando uma array 1-D
v2 = np.array([[7,8,9],[10,11,12]],dtype='int64')  #criando uma array 1-D
vetor_junto = np.concatenate((v1,v2), axis=0) #descobrir oq é axis
print(vetor_junto)


### Stack

In [ ]:
v1 = np.array([1, 2, 3]) #criando uma array 1-D
v2 = np.array([4, 5, 6]) #criando uma array 1-D
vetor = np.stack((v1, v2))
print(vetor)

### HStack

In [ ]:
v1 = np.array([1, 2, 3]) #criando uma array 1-D
v2 = np.array([4, 5, 6]) #criando uma array 1-D
vetor = np.hstack((v1, v2))
print(vetor)

### VStack

In [ ]:
v1 = np.array([1, 2, 3]) #criando uma array 1-D
v2 = np.array([4, 5, 6]) #criando uma array 1-D
vetor = np.vstack((v1, v2))
print(vetor)

### DStack

In [ ]:
v1 = np.array([1, 2, 3])  #criando uma array 1-D
v2 = np.array([4, 5, 6]) #criando uma array 1-D
vetor = np.dstack((v1, v2))
print(vetor)

# **Filtering**

### Where

In [ ]:
v = np.arange(1,30,dtype='float32') #criando uma array 1-D do tipo float32
pares = np.where(v % 2 != 0) #variavel = tupla com array apenas com index com numeros pares
print(pares)


### Condition

In [ ]:
"""
Obter alguns elementos de uma matriz existente e criar uma nova matriz a partir deles é chamado de filtering .
No NumPy, você filtra uma matriz usando uma lista de índices booleanos .
Se o valor em um índice for True esse elemento estiver contido na matriz filtrada, se o valor nesse índice for False 
esse elemento vai ser excluído da matriz filtrada.
"""
v = np.arange(1,4) #array de 1 a 3
filtro = [True, False,False] #Lista com msm numero do tamanho da array só que me bool
vetor = v[filtro] #variavel filtrada só com os valores True
print(vetor)



In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7]) #criando array
filter_v = (v % 2 == 0) #variavel recebendo o metodo de verificacao do True
vetor = v[filter_v] #variavel filtrada só com os valores True
print(filter_v)
print(vetor)

# **Searchsort**

In [ ]:
v = np.array([6,7,8,4,3,6,7,2,2,7,8,5,5,1,0,0,0,5,4,2,1,7,8])
x = np.searchsorted(v, 7) #O método inicia a pesquisa a partir da esquerda e retorna o primeiro índice em que o número 
#7 não é maior que o próximo valor.
print(x)


In [ ]:
v = np.array([6, 7, 8, 4,1,2,3,5,8,3,34,7,4,5,8,3,23,15,2,1,4,6,2])
x = np.searchsorted(v, 5,side='right') #O método inicia a pesquisa a partir da dirita e retorna o primeiro índice em
#que o número 4 não é maior que o próximo valor.
print(x) 

In [ ]:
v = np.array([1, 3, 5, 7])
x = np.searchsorted(v, [2, 4, 6]) #índices onde os valores 2, 4 e 6 devem ser inseridos para ficar em ordem
print(x)

In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7]) #criando array
# Create an empty list
filter_v = []

# go through each element in v
for element in v:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_v.append(True)
  else:
    filter_v.append(False)

vetor = v[filter_v] #variavel filtrada só com os valores True

print(filter_v)
print(vetor)

# **Shape**

In [ ]:
v = np.array([[1, 2, 3, 4], [3,6, 7, 8]]) #array de 2 dimensoes com 2 matrizes 4 valores cada
print(v.shape)

In [ ]:
v = np.array([1, 2, 3, 4]) #array de 4 valores 1-D
print(v.shape)

In [ ]:
v = np.array([1, 2, 3, 4],ndmin=5) #array de 4 valores 1-D
print(v.shape)
print(v.dtype)
print(v.ndim)

# **Reshape**

In [58]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],dtype='float32') #criando array 1-D 
vetor = v.reshape(4, 3) #nova array com msm valores só que com 4 linhas e 3 colunas
print(vetor)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],dtype='int32') #criando array 1-D 
vetor = v.reshape(2,2,3) #nova array com msm valores só que com 2 matrizes com 2 linhas e 3 colunas
print(vetor)

In [ ]:
v = np.array([[1,2,3],[4,5,6]],dtype='float64')
vetor = v.reshape(-1)#achatar matrizes transformando 2-D em 1-D
print(vetor)

# **Split**

In [ ]:
v = np.array([1, 2, 3, 4, 5, 6])
vetor = np.array_split(v, 3) #dividimos a matriz em 3 partes (O valor de retorno é uma matriz que contém três matrizes.)
print(vetor)
print(vetor[0])# [1,2]
print(vetor[1])# [3,4]
print(vetor[2])# [5,6]

In [ ]:
#é melhor usar o array_split() pq o split se o numero foi diferente dar erro
v = np.array([1, 2, 3, 4, 5, 6]) #dividimos a matriz em 4 partes (O valor de retorno é uma matriz que contém 4 matrizes.)
vetor = np.split(v, 4)
print(vetor) #erro

In [ ]:
#é melhor usar o array_split() pq o split se o numero foi diferente dar erro
v = np.array([1, 2, 3, 4, 5, 6]) #dividimos a matriz em 4 partes (O valor de retorno é uma matriz que contém 4 matrizes.)
vetor = np.array_split(v, 4)
print(vetor) #sem erro 

In [ ]:
v = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
vetor = np.array_split(v, 3) #transformou em 3 matriz com 2 matrizes cada
print(vetor)

In [ ]:
##Use o hsplit() vsplit() e dsplit() tambem  em split (FAZER DPS) os testes

# **Slicing**

In [ ]:
v = np.array([1, 2, 3, 4, 5, 6, 7])
print(v[1:4]) #retornando determinada parte da array

In [ ]:
v = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(v[1, 1:4])#retornando determinada parte da array da segundo array

In [ ]:
v = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) #entender
print(v[0:2, 1:4])

# **Indexing**

In [ ]:
v = np.array([1, 2, 3, 4],dtype=int) #criando uma array
v[0] = 4 #transformando o valor da posicao 0 da array
print(v)
print(v[0])  
print(v[1] + v[2]) #soma de dois valores

In [ ]:
v = np.array([1, 2, 3, 4,5,6,7],dtype=int) #criando uma array
v[3:] = 25 #transformando os valores da posicao 2 ate os final em 25
print(v) 


In [ ]:
v = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(v[0,3]) #acessando o valor da primeira matriz na posicao 3

In [ ]:
v = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(v[1,0,2]) #acessando o valor do primeiro conjunto de matriz,acessando a primeira e retornando o index 2

In [ ]:
v = np.array([1, 2, 3]) 
for index in v: #se for matriz 1-D printa numero por numero
  print(index, end=' ')

In [ ]:
v = np.array([[1, 2, 3], [4, 5, 6]])
for index in v: #se for matriz 2-D printa matriz por matriz
  print(index, end=' ')

In [ ]:
v = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for index in v: #se for matriz 3-D printa matriz por matriz
  print(index, end=' ')

In [ ]:
v = np.array([[1, 2, 3], [4, 5, 6]]) #para printar todos os nuemeros precisa de n for para n-D
for x in v:
  for y in x:
    print(y,end=' ')

In [ ]:
v = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in v: #para printar todos os nuemeros precisa de n for para n-D
  for y in x:
    for z in y:
      print(z,end=' ')

### Nditer

In [ ]:
"""
A função nditer() é uma função auxiliar que pode ser usada de iterações muito básicas a muito avançadas. 
Ele resolve alguns problemas básicos que enfrentamos na iteração, vamos analisá-lo com exemplos.
"""
v = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(v): #evita n for's' caso tenha uma matriz multidimensional grande
  print(x,end= ' ')

In [ ]:
#Itenerar com tamanhos diferentes (ENTENDER)
v = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(v[:, ::2]):
  print(x,end = ' ')

In [ ]:
"""
Podemos usar o op_dtypes argumento e passá-lo para o tipo de dados esperado para alterar o tipo de dados dos elementos 
durante a iteração.O NumPy não altera o tipo de dados do elemento no local (onde o elemento está na matriz), portanto,
ele precisa de algum outro espaço para executar esta ação, esse espaço extra é chamado de buffer e para habilitá-lo na 
nditer() passagem flags=['buffered'].
"""

v = np.array([1, 2, 3])
for x in np.nditer(v, flags=['buffered'], op_dtypes=['S']):
  print(x)

### Ndenumerate()

In [ ]:
"""
Enumeração significa mencionar o número de sequência de algumas coisas uma a uma.
Às vezes, exigimos o índice correspondente do elemento durante a iteração, o ndenumerate() método pode ser usado 
para esses casos.
"""

v = np.array([1, 2, 3])
for idx, x in np.ndenumerate(v):
  print(idx, x)

In [ ]:
v = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(v):
  print(idx, x)

# **Copy and View**

In [ ]:
"""
A principal diferença entre uma cópia e uma visualização de uma matriz é que a cópia é uma nova matriz,
e a visualização é apenas uma visualização da matriz original.
A cópia possui os dados e quaisquer alterações feitas na cópia não afetarão a matriz original, e quaisquer alterações
feitas na matriz original não afetarão a cópia.
A visualização não possui os dados e quaisquer alterações feitas na visualização afetarão a matriz original,
e quaisquer alterações feitas na matriz original afetarão a visualização.

"""

v = np.array([1, 2, 3, 4, 5]) #criando array
copia = v.copy() #variavel sendo atribuida para a copia dela
view = v.view() #variavel sendo atribuida para a view dela
v[0] = 42 #mudando o valor de uma posicao da array, acarretara na mudanca do view tb

print(v) 
print(copia) 
print(copia.base) #return None because the array have data (verificador de dados)
print(view) 
print(view.base) #return array because do not have data (verificador de dados)

In [ ]:
#Voce pode fazer mudanças com a função view()

v = np.array([1, 2, 3, 4, 5]) #criando array
view = v.view() #variavel sendo atribuida para a view dela
view[0] = 31 #mudando o valor de uma posicao do view, acarretara na mudança tb da array  
print(v)
print(view)

# **Math Operations**

In [ ]:
from scipy import stats
v = np.array([2,2,456,7,3,2,12,6,4,2,1]) #retorna uma array 1-D
print(min(v)) #retorna o valor minimo
print(max(v))#retorna o valor maximo
print(sum(v)) #retorna a soma dos valores
print(stats.mode(v))#retorna a moda
print(np.median(v)) #retorna a mediana
print(np.mean(v)) #retorna a media dos valores
print(np.std(v)) #retorna o desvio padrao
print(np.var(v)) #retorna a variancia


### Percentil

In [ ]:
'''
Qual é o percentil 75? A resposta é 43, o que significa que 75% das pessoas têm 43 anos ou menos.
O módulo NumPy possui um método para encontrar o percentil especificado:

'''

ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
x = np.percentile(ages, 2)
print(x)